name: main x64

on:
  push:
    branches:
      - main

  workflow_dispatch:
    branches:
      - main

jobs:
  call-workflow:
    uses: layer-3-communications/.github/.github/workflows/build-haskell.yaml@main
    with:
      build-arch: x64
      slack-name: ${{ github.ref_name }}
    secrets: inherit
